version: '3.9'
services:
  jupyterlab:
    container_name: jupyterlab
    build: .
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - ./:/work
    working_dir: '/work'
    tty: true
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --no-browser